spring:
  datasource:
    url: change me
    username: change me
    password: change me
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: create
    open-in-view: false
server:
  error:
    whitelabel:
      enabled: false

# jwt configuration
jwt:
  secret-key: change me

# elasticsearch configuration
elasticsearch:
  host: change me
  port: 9200
  username: elastic
  password: change me
  encodedApiKey: change me
  fingerprint: change me

# toss configuration
toss:
  api-key: change me
